apiVersion: 1

datasources:
  - name: Courtside Prometheus
    type: prometheus
    uid: courtside-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
