bookingCard.member=Member booking
bookingCard.training=Training
bookingCard.leagueMatch=League match
bookingCard.courtClosed=Court closed
participantCard.ballMachine=Ball machine
participantCard.lookingForAPartner=Looking for a partner
ruleSet.standard=Standard
ruleSet.youth=Youth
membershipType.active=Active
membershipType.youth=Youth
