CREATE TABLE message_record (
    id            uuid        PRIMARY KEY,
    -- The account is what erases a member from this log, so the reference is real and cascades.
    account_id    uuid        NOT NULL REFERENCES user_account ON DELETE CASCADE,
    kind          text        NOT NULL,
    state         text        NOT NULL,
    message_id    text        NOT NULL,
    reason        text,
    status_code   text,
    queued_at     timestamptz NOT NULL,
    -- "Newest first" is this log's whole promise and a clock cannot order two messages queued
    -- inside one of its ticks; BY DEFAULT because the test baseline restore names every column.
    queued_seq    bigint      GENERATED BY DEFAULT AS IDENTITY,
    settled_at    timestamptz,

    CONSTRAINT message_record_kind_known CHECK (
        kind IN ('CREDENTIALS_NEW_ACCOUNT', 'CREDENTIALS_PASSWORD_RESET')),
    CONSTRAINT message_record_state_known CHECK (
        state IN ('QUEUED', 'HANDED_OVER', 'REFUSED', 'FAILED')),
    CONSTRAINT message_record_settled_with_its_state CHECK (
        (state = 'QUEUED') = (settled_at IS NULL))
);

CREATE UNIQUE INDEX message_record_page_idx ON message_record (queued_seq DESC);
CREATE INDEX message_record_account_idx ON message_record (account_id, queued_seq DESC);
CREATE INDEX message_record_state_idx ON message_record (state, queued_seq DESC);
